name: unetattention-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scikit-learn
  - pillow
  - scikit-image
  - matplotlib
  - hydra-core
  - omegaconf
  - mlflow
  - optuna
  - ipykernel
  - torchmetrics
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch>=2.7.0
      - torchvision
      - torchaudio
      - torchxrayvision
      - hydra-optuna-sweeper